"use client";

import { useEffect, useState } from "react";

type Partner = { id: string; name: string; approved: boolean; user: { email: string; name: string | null } };
type Detail = { id: string; name: string; approved: boolean; user: { email: string; name: string | null }; commerceChannels: { id: string; label: string; status: string; referralActorId: string | null; referralLinkId: string | null }[]; commerceSeats: { id: string; displayName: string; email: string; commercialRole: string; status: string }[] };

export default function PartnerSupportPage() {
  const [partners, setPartners] = useState<Partner[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { void fetch("/api/v1/admin/partner-support").then(async r => { const d = await r.json(); if (!r.ok) setMessage(d.error ?? "Unable to load partners"); else if (!d.partners?.length) setMessage("No partner profiles are available yet."); else setPartners(d.partners); }).catch(() => setMessage("Unable to load partners. Please refresh or contact support.")); }, []);
  const open = async (id: string) => { setMessage("Loading audited workspace…"); const r = await fetch(`/api/v1/admin/partner-support?partnerId=${encodeURIComponent(id)}`); const d = await r.json(); if (r.ok) { setDetail(d.partner); setMessage("Read-only review recorded in the audit log."); } else setMessage(d.error ?? "Unable to open workspace"); };
  return <main className="dashboard-canvas"><div className="dashboard-body"><div className="dash-eyebrow">PRIMARY SUPPORT CONSOLE</div><h1 className="page-header">Partner support</h1><p style={{ color: "var(--color-text-secondary)", maxWidth: 760 }}>Denzil’s Superadmin workspace for diagnosing partner setup without accessing a partner’s email, password, or bank account. Opening a workspace is read-only and audited.</p>{message && <p style={{ fontSize: 13, color: "var(--color-text-secondary)" }}>{message}</p>}<div className="panel" style={{ marginTop: 24 }}><div className="panel-title">Partners</div>{partners.map(p => <button key={p.id} onClick={() => void open(p.id)} style={{ display: "flex", width: "100%", justifyContent: "space-between", textAlign: "left", padding: "16px 0", background: "transparent", border: 0, borderTop: "1px solid var(--color-border)", color: "inherit", cursor: "pointer" }}><span><strong>{p.name}</strong><br /><small>{p.user.email}</small></span><span>{p.approved ? "Approved partner" : "Pending approval"} · Open workspace →</span></button>)}</div>{detail && <section className="panel" style={{ marginTop: 24 }}><div className="panel-title">{detail.name} — read-only workspace</div><p className="panel-subtitle">No seller invitations, QR activations, commission terms, or payout actions can be made here.</p><h3>Channels</h3>{detail.commerceChannels.length ? detail.commerceChannels.map(c => <p key={c.id}>{c.label}: <strong>{c.status}</strong></p>) : <p>No partner direct channel has been drafted.</p>}<h3>Seller seats</h3>{detail.commerceSeats.length ? detail.commerceSeats.map(s => <p key={s.id}><strong>{s.displayName}</strong> · {s.email} · {s.commercialRole.replaceAll("_", " ")} · {s.status}</p>) : <p>No seller seats have been drafted.</p>}</section>}</div></main>;
}
