"use client";

import { FormEvent, useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";

type LinkData = { code: string; url: string | null; isActive: boolean; clickCount: number };
type Partner = { id: string; name: string; approved: boolean; user: { email: string; name: string | null } };
type Channel = { id: string; label: string; status: string; referralLink: LinkData | null };
type Seat = { id: string; displayName: string; email: string; commercialRole: string; status: string; provisionedUserId: string | null; referralLink: LinkData | null };
type Detail = Partner & { commerceChannels: Channel[]; commerceSeats: Seat[] };

const grid = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 240px), 1fr))", gap: 12 } as const;
const field = { width: "100%", minHeight: 48 } as const;

function QRCard({ link }: { link: LinkData }) {
  if (!link.url) return null;
  return <div style={{ display: "grid", gridTemplateColumns: "96px 1fr", gap: 14, alignItems: "center", marginTop: 14 }}>
    <div style={{ background: "white", padding: 8, borderRadius: 10 }}><QRCodeSVG value={link.url} size={80} style={{ display: "block" }} /></div>
    <div style={{ minWidth: 0 }}><strong>{link.code}</strong><div style={{ fontSize: 12, overflowWrap: "anywhere", color: "var(--color-text-secondary)" }}>{link.url}</div><small>{link.clickCount} scans</small></div>
  </div>;
}

export default function PartnerSupportPage() {
  const [partners, setPartners] = useState<Partner[]>([]); const [detail, setDetail] = useState<Detail | null>(null); const [message, setMessage] = useState(""); const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [role, setRole] = useState("TEAM_SELLER"); const [partnerName, setPartnerName] = useState(""); const [partnerEmail, setPartnerEmail] = useState(""); const [busy, setBusy] = useState("");
  const loadPartners = async () => { const r = await fetch("/api/v1/admin/partner-support"); const d = await r.json(); if (!r.ok) setMessage(d.error ?? "Unable to load partners"); else setPartners(d.partners ?? []); };
  useEffect(() => { void loadPartners().catch(() => setMessage("Unable to load partners. Please refresh.")); }, []);
  const open = async (id: string) => { setMessage("Loading audited workspace…"); const r = await fetch(`/api/v1/admin/partner-support?partnerId=${encodeURIComponent(id)}`); const d = await r.json(); if (r.ok) { setDetail(d.partner); setMessage("Workspace review recorded in the audit log."); } else setMessage(d.error ?? "Unable to open workspace"); };
  const addSeller = async (e: FormEvent) => { e.preventDefault(); if (!detail) return; const r = await fetch("/api/v1/admin/partner-support", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ partnerId: detail.id, displayName: name, email, commercialRole: role }) }); const d = await r.json(); if (!r.ok) return setMessage(d.error ?? "Unable to save seller"); setName(""); setEmail(""); setMessage("Seller draft saved."); await open(detail.id); };
  const invite = async (seatId: string) => { setBusy(seatId); const r = await fetch(`/api/v1/admin/partner-support/seats/${encodeURIComponent(seatId)}/invite`, { method: "POST" }); const d = await r.json(); setBusy(""); if (!r.ok) return setMessage(d.error ?? "Unable to send invitation"); setMessage(`Secure sign-in email sent to ${d.result.email}.`); if (detail) await open(detail.id); };
  const invitePartner = async () => { if (!detail) return; setBusy(detail.id); const r = await fetch(`/api/v1/admin/partner-support/${encodeURIComponent(detail.id)}/invite`, { method: "POST" }); const d = await r.json(); setBusy(""); setMessage(r.ok ? `Secure partner sign-in sent to ${d.email}.` : (d.error ?? "Unable to send sign-in")); };
  const provisionPartner = async (e: FormEvent) => { e.preventDefault(); const r = await fetch("/api/v1/admin/partner-support/provision", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: partnerName, email: partnerEmail }) }); const d = await r.json(); if (!r.ok) return setMessage(d.error ?? "Unable to provision partner"); setPartnerName(""); setPartnerEmail(""); await loadPartners(); await open(d.partner.id); };
  const channelAction = async (kind: "partner" | "seller", id: string, action: "activate" | "pause" | "rotate") => { if (!detail) return; const key = `${id}:${action}`; setBusy(key); const path = kind === "partner" ? `channels/${id}` : `seats/${id}/channel`; const r = await fetch(`/api/v1/admin/partner-support/${path}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action }) }); const d = await r.json(); setBusy(""); setMessage(r.ok ? `${kind === "partner" ? "Partner" : "Seller"} channel updated.` : (d.error ?? "Unable to update channel")); if (r.ok) await open(detail.id); };
  const createDirect = async () => { if (!detail) return; setBusy("direct"); const r = await fetch("/api/v1/admin/partner-support", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "create_direct_channel", partnerId: detail.id }) }); const d = await r.json(); setBusy(""); setMessage(r.ok ? "Partner room-card channel drafted." : (d.error ?? "Unable to draft channel")); if (r.ok) await open(detail.id); };
  return <main className="dashboard-canvas"><div className="dashboard-body" style={{ maxWidth: 1120, margin: "0 auto", paddingInline: 16 }}>
    <div className="dash-eyebrow">PRIMARY SUPPORT CONSOLE</div><h1 className="page-header">Partner support</h1><p style={{ color: "var(--color-text-secondary)", maxWidth: 760 }}>Audited support without accessing a partner’s email, password, or bank account. Superadmin controls activation, pausing, and QR rotation.</p>
    {message && <p role="status" style={{ fontSize: 13, padding: 12, borderRadius: 10, background: "var(--layer-2)" }}>{message}</p>}
    <div className="panel" style={{ marginTop: 20 }}><div className="panel-title">Partners</div><div style={grid}>{partners.map((p) => <button key={p.id} onClick={() => void open(p.id)} className="btn btn-secondary" style={{ minHeight: 58, justifyContent: "space-between", textAlign: "left", whiteSpace: "normal" }}><span><strong>{p.name}</strong><br /><small>{p.user.email}</small></span><span>Open →</span></button>)}</div></div>
    <section className="panel" style={{ marginTop: 20 }}><div className="panel-title">Provision partner</div><p className="panel-subtitle">Creates the account and its standard direct-channel draft. Nothing is emailed or activated automatically.</p><form onSubmit={provisionPartner} style={grid}><input style={field} required placeholder="Partner name" value={partnerName} onChange={(e) => setPartnerName(e.target.value)} /><input style={field} required type="email" placeholder="Partner email" value={partnerEmail} onChange={(e) => setPartnerEmail(e.target.value)} /><button className="btn btn-primary" style={field} type="submit">Provision partner</button></form></section>
    {detail && <section className="panel" style={{ marginTop: 20 }}><div className="panel-title">{detail.name}</div><p className="panel-subtitle">Partner owner: {detail.user.email}</p><button className="btn btn-primary" style={{ minHeight: 48 }} disabled={busy === detail.id} onClick={() => void invitePartner()}>Send partner secure sign-in</button>
      <h2 style={{ fontSize: 20, marginTop: 28 }}>Room-card channel</h2>{detail.commerceChannels.length === 0 && <button className="btn btn-primary" style={{ minHeight: 48 }} disabled={Boolean(busy)} onClick={() => void createDirect()}>Create standard room-card channel</button>}{detail.commerceChannels.map((c) => <article key={c.id} style={{ border: "1px solid var(--color-border)", borderRadius: 14, padding: 16 }}><strong>{c.label}</strong> · {c.status}<div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}>{c.status !== "ACTIVE" && <button className="btn btn-primary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void channelAction("partner", c.id, "activate")}>Activate room QR</button>}{c.status === "ACTIVE" && <button className="btn btn-secondary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void channelAction("partner", c.id, "pause")}>Pause</button>}{c.referralLink && <button className="btn btn-secondary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void channelAction("partner", c.id, "rotate")}>Rotate QR</button>}</div>{c.referralLink && <QRCard link={c.referralLink} />}</article>)}
      <h2 style={{ fontSize: 20, marginTop: 28 }}>Add seller</h2><form onSubmit={addSeller} style={grid}><input style={field} required placeholder="Name" value={name} onChange={(e) => setName(e.target.value)} /><input style={field} required type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} /><select style={field} value={role} onChange={(e) => setRole(e.target.value)}><option value="TEAM_SELLER">Team seller</option><option value="CONCIERGE">Concierge</option><option value="PROMOTER">Promoter</option><option value="INFLUENCER">Influencer</option><option value="SPEAKER">Speaker</option><option value="SPONSOR">Sponsor</option></select><button className="btn btn-primary" style={field}>Save draft</button></form>
      <h2 style={{ fontSize: 20, marginTop: 28 }}>Seller channels</h2><div style={grid}>{detail.commerceSeats.map((s) => <article key={s.id} style={{ border: "1px solid var(--color-border)", borderRadius: 14, padding: 16, minWidth: 0 }}><strong>{s.displayName}</strong><div style={{ overflowWrap: "anywhere", fontSize: 13 }}>{s.email}</div><small>{s.commercialRole.replaceAll("_", " ")} · {s.status}</small><div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 12 }}>{s.status === "DRAFT" && <button className="btn btn-secondary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void invite(s.id)}>Invite</button>}{s.provisionedUserId && s.status !== "ACTIVE" && <button className="btn btn-primary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void channelAction("seller", s.id, "activate")}>Activate QR</button>}{s.status === "ACTIVE" && <button className="btn btn-secondary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void channelAction("seller", s.id, "pause")}>Pause</button>}{s.referralLink && <button className="btn btn-secondary" style={{ minHeight: 44 }} disabled={Boolean(busy)} onClick={() => void channelAction("seller", s.id, "rotate")}>Rotate</button>}</div>{s.referralLink && <QRCard link={s.referralLink} />}</article>)}</div>
    </section>}
  </div></main>;
}
