import { prisma } from "@/lib/prisma";
import { nanoid } from "nanoid";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://okuhospitality.com";

export interface GenerateLinkInput {
  referralActorId: string;
  referralAssignmentId?: string;
  pathHint?: string;
}

function buildCode(prefix = "REF"): string {
  return `${prefix}-${nanoid(8).toUpperCase()}`;
}

function buildUrl(code: string, pathHint?: string): string {
  // Canonical share path: /r/[code] — the public router resolves this through
  // the unified ReferralLink → ReferralActor → ReferralAssignment chain. We
  // keep `pathHint` support so callers that want a deep-link (e.g. straight
  // to a series page) can still use `?ref=` query — but the DEFAULT for new
  // links generated by the share wallet is the canonical /r/[code] path.
  if (pathHint) {
    const path = `/${pathHint.replace(/^\//, "")}`;
    return `${APP_URL}${path}?ref=${code}`;
  }
  return `${APP_URL}/r/${code}`;
}

/**
 * Generate a new referral link (and optionally a QR code stub) for an actor.
 * QR code data URL generation is async-ready; for now stores null — 
 * a BullMQ job can fill it in (Phase 3+ architecture).
 */
export async function generateReferralLink(input: GenerateLinkInput) {
  const actor = await prisma.referralActor.findUnique({
    where: { id: input.referralActorId },
  });
  if (!actor) throw new Error("ReferralActor not found");

  const code = buildCode();
  const url = buildUrl(code, input.pathHint);

  return prisma.referralLink.create({
    data: {
      referralActorId: input.referralActorId,
      referralAssignmentId: input.referralAssignmentId ?? null,
      code,
      url,
      qrCodeDataUrl: null,
      isActive: true,
    },
  });
}

/**
 * Get all active links for an actor.
 */
export async function getActorLinks(referralActorId: string) {
  return prisma.referralLink.findMany({
    where: { referralActorId, isActive: true },
    orderBy: { createdAt: "desc" },
  });
}

/**
 * Deactivate a referral link by id.
 */
export async function deactivateLink(id: string) {
  return prisma.referralLink.update({
    where: { id },
    data: { isActive: false },
  });
}

/**
 * Track a click on a referral link (called server-side when ?ref= param is seen).
 */
export async function trackLinkClick(code: string): Promise<{ found: boolean; referralActorId?: string }> {
  const link = await prisma.referralLink.findUnique({ where: { code } });
  if (!link || !link.isActive) return { found: false };

  await prisma.referralLink.update({
    where: { id: link.id },
    data: { clickCount: { increment: 1 }, lastClickedAt: new Date() },
  });

  return { found: true, referralActorId: link.referralActorId };
}
