export type RoleKey =
  | "VISITOR"
  | "ATTENDEE"
  | "INFLUENCER"
  | "PARTNER"
  | "INVESTOR"
  | "REFERRER"
  | "STAFF_OKU"
  | "STAFF_CATCH"
  | "ADMIN_COMMERCIAL"   // Legacy — stripped to empty permissions; do not assign to new users
  | "ADMIN_IR"
  | "ADMIN_HR"
  | "ADMIN_FINANCE"
  | "SUPERADMIN"
  | "RESTAURANT_HOST"
  | "STREETSIDE_HOST"
  | "FB_DIRECTOR"         // Restaurant F&B operations — menus, experiences, spaces, operational analytics
  | "RESTAURANT_SUPERVISOR"; // Live-service host portal only — no /admin shell access

export type PermissionKey =
  | "public:read"
  | "account:read"
  | "account:write"
  | "series:read"
  | "series:purchase"
  | "influencer:read"
  | "influencer:write"
  | "partner:read"
  | "partner:write"
  | "ir:read"
  | "ir:write"
  | "hr:read"
  | "hr:write"
  | "staff:sops:read"
  | "staff:sops:ack"
  | "referrer:read"
  | "admin:audit:read"
  | "admin:security:read"
  | "admin:users:edit"
  | "admin:payments:refund"
  | "admin:payouts:write"
  | "admin:compensation:read"
  | "admin:compensation:write"
  | "admin:menus:read"
  | "admin:menus:edit"
  | "admin:revenue:read"
  | "admin:revenue:write"
  | "partner:invite:write"
  | "partner:hosts:write"
  | "partner:earnings:read"
  | "host:reservations:checkin"
  | "tickets:checkin"
  | "admin:tickets:read"
  | "admin:tickets:write"
  | "admin:beneficiaries:summary"
  | "admin:beneficiaries:detail"
  | "admin:beneficiaries:write"
  // Scoped operations permissions introduced with FB_DIRECTOR / RESTAURANT_SUPERVISOR
  | "admin:spaces:read"
  | "admin:spaces:write"
  | "admin:operations:read"
  | "admin:operations:write"
  | "admin:analytics:operations:read"
  | "admin:orders:read"
  | "admin:orders:write"
  | "admin:experiences:write";
